import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Next Boss",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-red-700 text-white px-4">
          <h2>Logo</h2>
          <ul>About</ul>
          <ul>Contact</ul>
          <ul>Home</ul>
        </nav>

        <div>{children}</div>
        <footer className="bg-gray-500 text-white">This is my footer</footer>
      </body>
    </html>
  );
}
